import 'package:clothing_ecommerce/core/utils/themes/app_colors.dart';
import 'package:flutter/material.dart';

class AppThemes {
  static ThemeData get lightTheme => ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
      seedColor: AppColors.primaryColor,
      primary: AppColors.primaryColor,
      onPrimary: AppColors.white,
      surface: AppColors.white,
      surfaceTint: AppColors.white,
      onSurfaceVariant: AppColors.grey,
      onSurface: AppColors.grey,
      surfaceContainer: AppColors.dark,
      surfaceContainerHighest: AppColors.lightGrey1,
      secondary: AppColors.black,
      onSecondary: AppColors.darkGrey,
      shadow: AppColors.lightGrey2,
      error: AppColors.red,
      tertiary: AppColors.lightGrey3,
      secondaryContainer: AppColors.green,
      tertiaryContainer: AppColors.gold,
      primaryContainer: AppColors.orange,
    ),
    // textSelectionTheme: TextSelectionThemeData(
    //   cursorColor: AppColors.white,
    //   selectionColor: AppColors.brown,
    //   selectionHandleColor: AppColors.white,
    // ),
  );
  static ThemeData get darkTheme => ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
      seedColor: AppColors.primaryColorDarkTheme,
      primary: AppColors.primaryColorDarkTheme,
      onPrimary: AppColors.white,
      surface: AppColors.darkSurface,
      surfaceTint: AppColors.dark,
      surfaceContainer: AppColors.dark,
      onSurfaceVariant: AppColors.grey,
      onSurface: AppColors.grey,
      surfaceContainerHighest: AppColors.dark,
      secondary: AppColors.white,
      onSecondary: AppColors.darkGrey,
      shadow: AppColors.lightGrey2,
      error: AppColors.red,
      tertiary: AppColors.darkSurface,
      secondaryContainer: AppColors.green,
      tertiaryContainer: AppColors.gold,
      primaryContainer: AppColors.orange,
    ),
    // textSelectionTheme: TextSelectionThemeData(
    //   cursorColor: AppColors.white,
    //   selectionColor: AppColors.brown,
    //   selectionHandleColor: AppColors.white,
    // ),
  );
  static ThemeData get blueTheme => ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
      seedColor: AppColors.darkBlue,
      primary: AppColors.darkBlue,
      onPrimary: AppColors.white,
      surface: AppColors.white,
      onSurfaceVariant: AppColors.grey,
      onSurface: AppColors.grey,
      surfaceContainer: AppColors.dark,
      surfaceContainerHighest: AppColors.lightGrey1,
      secondary: AppColors.black,
      onSecondary: AppColors.darkGrey,
      shadow: AppColors.lightGrey2,
      error: AppColors.red,
      tertiary: AppColors.lightGrey3,
      secondaryContainer: AppColors.green,
      tertiaryContainer: AppColors.gold,
      primaryContainer: AppColors.orange,
    ),
    // textSelectionTheme: TextSelectionThemeData(
    //   cursorColor: AppColors.white,
    //   selectionColor: AppColors.brown,
    //   selectionHandleColor: AppColors.white,
    // ),
  );
  static ThemeData get orangeTheme => ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
      seedColor: AppColors.orange,
      primary: AppColors.orange,
      onPrimary: AppColors.white,
      surface: AppColors.white,
      onSurfaceVariant: AppColors.grey,
      onSurface: AppColors.grey,
      surfaceContainer: AppColors.dark,
      surfaceContainerHighest: AppColors.lightGrey1,
      secondary: AppColors.black,
      onSecondary: AppColors.darkGrey,
      shadow: AppColors.lightGrey2,
      error: AppColors.red,
      tertiary: AppColors.lightGrey3,
      secondaryContainer: AppColors.green,
      tertiaryContainer: AppColors.gold,
      primaryContainer: AppColors.orange,
    ),
    // textSelectionTheme: TextSelectionThemeData(
    //   cursorColor: AppColors.white,
    //   selectionColor: AppColors.brown,
    //   selectionHandleColor: AppColors.white,
    // ),
  );
  static ThemeData get purpleTheme => ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
      seedColor: AppColors.purple,
      primary: AppColors.purple,
      onPrimary: AppColors.white,
      surface: AppColors.white,
      onSurfaceVariant: AppColors.grey,
      onSurface: AppColors.grey,
      surfaceContainer: AppColors.dark,
      surfaceContainerHighest: AppColors.lightGrey1,
      secondary: AppColors.black,
      onSecondary: AppColors.darkGrey,
      shadow: AppColors.lightGrey2,
      error: AppColors.red,
      tertiary: AppColors.lightGrey3,
      secondaryContainer: AppColors.green,
      tertiaryContainer: AppColors.gold,
      primaryContainer: AppColors.orange,
    ),
    // textSelectionTheme: TextSelectionThemeData(
    //   cursorColor: AppColors.white,
    //   selectionColor: AppColors.brown,
    //   selectionHandleColor: AppColors.white,
    // ),
  );
}
